### ISSUE TITLE
add ASHS

### ISSUE THREAD

**Issue by stebo85** [stebo85/neurodocker-old-fork#8]

**Comment by stebo85** [comment]
added, needs testing.

**Comment by 0luhancheng0** [comment]
hi i wonder which version of neurodocker is this? the most recent version of neurodocker does not seem to have `--ashs` option

**Comment by stebo85** [comment]
Dear @0luhancheng0 - it's our fork of neurodocker and I haven't made a pull request back, because the neurodocker guys were quite busy and didn't merge pull request for a while. It's on my todo list to send a lot of our changes back upstream in the next weeks :)

**Comment by 0luhancheng0** [comment]
Thanks @stebo85 !
